strcpy(vettore[j], "                                                             `.-```                                 "); j++;
strcpy(vettore[j], "                                                          `/hNNNNmmdhs+/`                           "); j++;
strcpy(vettore[j], "                                   `                    .omMMMMMMMMMMMMMmy.                         "); j++;
strcpy(vettore[j], "                                   `h+`    -`          +NMMMMMMNmhs+:---sNm:                        "); j++;
strcpy(vettore[j], "                  ``            ++:-:dm+  oNo         yMMmNMMMN+`        /MNo`                      "); j++;
strcpy(vettore[j], "                 /my            .+hdmhmMy:yMm        -MMh`:dMy.           oMMy                      "); j++;
strcpy(vettore[j], "                `mM: `-.``        `.+dNMMNmMM:       yMMo :dNd`           `MMh                      "); j++;
strcpy(vettore[j], "           :    oMd.ymmso-           `yMMMMMMy       sMMy -sdy:`           NMs`                     "); j++;
strcpy(vettore[j], "          :N-  .NM+dMN.           ..` +MMMMMMN`      +MMdsmMMMNms`1CNOC+/:-mMso                     "); j++;
strcpy(vettore[j], "          .Md` /MMsMMy   -+o/.`.:ymmdyoMMMMMMN`      .MMMMMMMMMMMhmMMMMNmysNMo`                     "); j++;
strcpy(vettore[j], "           dMh /mMMMMy`-yNMNhdyNNo/odNMMMMMMMM/       NMMMMMMMMMd+d/smMho+-yd+.                     "); j++;
strcpy(vettore[j], "           oMMy+dMMMMMmNMm+. -oM+   `/MMMMMMMMd-      shdNMMMMMN- .s+s+-``--.+/-                    "); j++;
strcpy(vettore[j], "           +MMMMMMMMMMMMm.    `/      hMMMMMMMMNo`    `y:hMMMMNho- --hs/``  ` `-                    "); j++;
strcpy(vettore[j], "           hMMMMMMMMMMMM/             `oNMMMMMMMMdo:.` o:mMMMMMMMd---+NN+  `y-....``  ```           "); j++;
strcpy(vettore[j], "           mMMMMMMMMMMMM:  PRINDEFFE   `oMMMMMMMMMMm:.::mdNMMMMMNh/.`./dN  +//:-+h/+//+o+- ``       "); j++;
strcpy(vettore[j], "          +MMMMMMMMMMMMMm.          .:sdNMMMMMMMMMMMNs.`.-hMNMMmh/-.`/:+o -m sd//MNMMd`  `/hd-   ```"); j++;
strcpy(vettore[j], "         `mMMMMMMMMMMMMMMm+`   `./sdmMNMNNMMMMMMMMMMNh-:yNMMyodMNs-     `-my:-MNNMMMMM-.odds/`   .o:"); j++;
strcpy(vettore[j], "         /MMMMMMMMMMMMMMMNNdhhyhNMMhoo----:sdNMMMMMd/+dMMMMMMd/smNh`    -mMm/mMMMMMMdosNN+        ` "); j++;
strcpy(vettore[j], "         hMMMMMMMMMMNdo::--/odmMMN+         `-omMNyymMMMMMMMMMNy-.    ./mMMhdMMMMMMN`yms-`          "); j++;
strcpy(vettore[j], "        `NMMMMMMMMMy-`        .ym/             .hmNMMMMMMMMMMMMMd-`` -dMMMmhMMMMMMMd+ds.            "); j++;
strcpy(vettore[j], "        -NMMMMMMMMh`            ``             -+/sMMMMMMMMMMMMMmddh/..sMNhMMMMMMMMMMMmo``          "); j++;
strcpy(vettore[j], "        :NMMMMMMMM+-                      ``:.+s.sMMMMMMMMMMMMMMmNMMNm/.oyMMMMMMMMMMMMMhho.`        "); j++;
strcpy(vettore[j], "        /MMMMMMMMMs:                     -.smomNoMMMMMMMMMMMMMMMMMMMMMMNd//ymMMMMMMMMMMMMy:::`      "); j++;
strcpy(vettore[j], "        /MMMMMMMMMd-                   `sdydMNMmNMMMMMMMMMMMMMMMMMMMMMMMMd-../sNMMMMMMMMd+-         "); j++;
strcpy(vettore[j], "        /MMMMMMMMMM:                 `+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmms/`-+hmMMMMN+.          "); j++;
strcpy(vettore[j], "        /MMMMMMMMMMy               `+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms` `:oyN/            "); j++;
strcpy(vettore[j], "        /MMMMMMMNmMh-             /mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm/-   --   .`       "); j++;
strcpy(vettore[j], "        -MMMMMMMhNMmy           `/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhy/.-    ..:.     "); j++;
strcpy(vettore[j], "        `NMMMMMMMMMMd-        `/dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNN/`     ..-   "); j++;
strcpy(vettore[j], "         NMMMMMMMMMMNd     `-smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+` :-  ``  "); j++;
strcpy(vettore[j], "         dMMMMMMMMMMMMy.`-odMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs:m/ `. ."); j++;
strcpy(vettore[j], "         oMMMMMMMMMMMMMMmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo`ho."); j++;
strcpy(vettore[j], "         :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdoMd"); j++;
strcpy(vettore[j], "         `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm"); j++;
strcpy(vettore[j], "          dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm"); j++;
strcpy(vettore[j], "          yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm"); j++;
strcpy(vettore[j], "          /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm"); j++;
strcpy(vettore[j], "          :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm"); j++;
strcpy(vettore[j], "          `dmmmmmmhhhhhhhhhhhmmmmmmmmmmmdmmmmmmmmmmmmdmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm"); 