	strcpy(vettore[i], "                                         --/shmmmmmmmmmdssssss:.                                    \0");  i++;
	strcpy(vettore[i], "                                    :/syNNMMMMMMMMMMMMMMMMMMMMMNo-                                  \0");  i++;
	strcpy(vettore[i], "                                 -hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNm/                                \0");  i++;
	strcpy(vettore[i], "                               -hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdy-                             \0");  i++;
	strcpy(vettore[i], "                             -hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNho-                          \0");  i++;
	strcpy(vettore[i], "                          .sdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo:                        \0");  i++;
	strcpy(vettore[i], "                         smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN-                       \0");  i++;
	strcpy(vettore[i], "                       .yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd                       \0");  i++;
	strcpy(vettore[i], "                      .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo                      \0");  i++;
	strcpy(vettore[i], "                     oNMMMMMMMMmMMMMMMMMmMMMNhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN-                     \0");  i++;
	strcpy(vettore[i], "                     mMMMMMMMMo/:hmo:/:.--/+--:..ysysymNdy+hhdMMMMMMMMMMMMMMMMd                     \0");  i++;
	strcpy(vettore[i], "                     mMMMMMMMh-   -       -      --   -.:    -odMMMMMMMMMMMMMMMo                    \0");  i++;
	strcpy(vettore[i], "                     mMMMMMMMo                               :dNMMMMMMMMMMMMMMMN.                   \0");  i++;
	strcpy(vettore[i], "                     mMMMMMMMs                              :mMMMMMMMMMMMMMMMMMM.                   \0");  i++;
	strcpy(vettore[i], "                     sMMMMMMMy-                            -oMMMMMMMMMMMMMMMMMMM.                   \0");  i++;
	strcpy(vettore[i], "                     -MMMMMMMs                             yMMMMMMMMMMMMMMMMMMMM.                   \0");  i++;
	strcpy(vettore[i], "                     -MMMMMMMo--                           yNMMMMMMMMMMMMMMMMMMM:                   \0");  i++;
	strcpy(vettore[i], "                     sMMMMMMMNmNy-+-.-                    /MMMMMMMMMMMMMMMMMMMMMm-                  \0");  i++;
	strcpy(vettore[i], "                   .hMMMMMMMMMMMMNMNNdy:.--           .::yNMMMMMMMMMMMMMMMMMMMMMMN-                 \0");  i++;
	strcpy(vettore[i], "                   oNNMMMMMMMMMMMMNNNNMMmmd/      -  +NMMMNNmhNMMMMMMMMMMMMMMMMMMMd:                \0");  i++;
	strcpy(vettore[i], "                    .:NMMMMMMMMMMds++oyyyyo:      -.:dMhyMdddyNMMMMMMMMMMMMMMMMMMM/o.               \0");  i++;
	strcpy(vettore[i], "                      +MMMMMMhNNMMyoMmMMsyo.      hmMMNym/-NdMMNMMMMMMMMMMMMMMMMMMy +-              \0");  i++;
	strcpy(vettore[i], "                       NMMMm+-hsoh-:yhdo::: .- --oMMMMmoo//oshsNMMMMMMMMMMMMMMMMdymos-              \0");  i++;
	strcpy(vettore[i], "                   :   +MMMMNh+   --...--  -s. -omMMMMNs   ---.smmMMMMMMMMMMMMMMyhMMy               \0");  i++;
	strcpy(vettore[i], "                   .   -hMMMMMo-            - /sENNUPLAHh/--   -..dMMMMMMMMMMMMMMMMMo               \0");  i++;
	strcpy(vettore[i], "                     -+-.MMMMo--            -ymdyNMMMMMMMMmh+y:oy+NMMMMMMMMMMMMMMMMy                \0");  i++;
	strcpy(vettore[i], "                   o.--- MMMd              .:h-  .mMMMMMMmds.oyosdMMMMMMMMMMMMMMMMy-                \0");  i++;
	strcpy(vettore[i], "                   :Ny--.NMN:             -md-    :NMMMMM/      hMMMMMMMMMMMMMMMMy                  \0");  i++;
	strcpy(vettore[i], "                   -smo-.oMm/             o/.-    .dMMMMMm-     mMMMMMMMMMMMMMMNy-                  \0");  i++;
	strcpy(vettore[i], "                     ./+:+MM: --           --o:- -NMMNmMMMh:.-  /MMMMMMMMMMNhs/.                    \0");  i++;
	strcpy(vettore[i], "                       -sNMMd---        -:.:/vettoreMMMMMMMMNd- :MMMMMMMMMMh                        \0");  i++;
	strcpy(vettore[i], "                         +mMMd:-       garbo/---dhdyNMMMMMMMMMmosMMMMMMMMMMy                        \0");  i++;
	strcpy(vettore[i], "                          hMMMs:       ..--    .o.- -+hdMMMMMNMMMMMMMMMMMMMh/++++shhhhs+:..--       \0");  i++;
	strcpy(vettore[i], "                          hMMMM+ +:     :++.-...---.sNMMMMMMm:mMMMMMMMMMMMMMMMMMMMMMMMMMMMMhhy+--   \0");  i++;
	strcpy(vettore[i], "                          hMMMM+ -N-   -+ydo:/ho///hmMMMMMMNh/mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmh:. \0");  i++;
	strcpy(vettore[i], "                         -mMMMMh.-M+.-         -----+NMMMMMNddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:\0");  i++;
	strcpy(vettore[i], "                       .-mMMMMMMmhMMNy        -::+doo+soyoodMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/\0");  i++;
	strcpy(vettore[i], "                    --+mMMMMMMMMMmMMMNs-           -my+/symMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMM/\0");  i++;
	strcpy(vettore[i], "               -./yymMMMMMMMMMMMMMMMMMMN++-        -mMMMMMMMMMMMMMMMMMMMMMMMMMMMMoNMMMMMMMMMMMMMMMM+\0");  i++;
	strcpy(vettore[i], "            --+dNMMMMMMMMMMMMMMMMMMNMMMMMMh--      -dMMMMMMMMMMMMMMMMMMMMMMMMMMMM+NMMMMMMMMMMMMMMMMN\0");  i++;
	strcpy(vettore[i], "         -/hNMMMMMMMyNMMMMMMMMMMMM:.dMMMMMMsds/-.-/dMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:NMMMMMMMMMMMMMMMMM\0");  i++;
	strcpy(vettore[i], "      -+yMMMMMMMMMMMomMMMMMMMMMMMM:  sMMMMMMMMMMdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd NMMMMMMMMMMMMMMMMM\0");  i++;
	strcpy(vettore[i], "   -.oNMMMMMMMMMMMMMomMMMMMMMMMMMMy  -hMMMMh--smMMMMhsmMMMMMMMMMMMNMMMMMMMMMMMMMd+MMMMMMMMMMMMMMMMMM\0");  i++;
	strcpy(vettore[i], "ooymMMMMMMMMMMMMMMMM+mMMMMMMMMMMMMN-   /MMMy-   :o+-  yMMMMMMMMMMMmsMMMMMMMMMMMMysMMMMMMMMMMMMMMMMMM\0");  i++;
	strcpy(vettore[i], "MMMMMMMMMMMMMMMMMMd+oMMMMMMMMMMMMMMy.  .dMMMd--      -dMMMMMMMMMMy. dMMMMMMMMMMM.sMMMMMMMMMMMMMMMMMM\0");  i++;
	strcpy(vettore[i], "MMMMMMMMMMMMMMMMMd-oMMMMMMMMMMdMMMMMs   -oNMmmo     :NMNNMMMMMMm/- -MMMMMMMMMMMM/NMMMMMMMMMMMMMMMMMM\0");  i++;
	strcpy(vettore[i], "MMMMMMMMMMMMMMMMN-/MMMMMMMMMMMdMMMMMd.    :M+-    o/y+---MMMMMN/   -MMMMMMMMMMMh:MMMMMMMMMMMMMMMMMMM\0");  i++;
	strcpy(vettore[i], "MMMMMMMMMMMMMMMM+:MMMMMMMMMMMo/mMMMMMs     yN/           sMMMM+    -MMMMMMMMMMMomMMMMMMMMMMMMMMMMMMM\0");  
